/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_lvgldemo_LVGLDemo */

#ifndef _Included_com_example_lvgldemo_LVGLDemo
#define _Included_com_example_lvgldemo_LVGLDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_lvgldemo_LVGLDemo
 * Method:    getIntArray
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_lvgldemo_LVGLDemo_getIntArray
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_lvgldemo_LVGLDemo
 * Method:    main
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_lvgldemo_LVGLDemo_main
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
